server.port=8080

spring.application.name=api-gateway

# Routes — /api/users/** goes to service-utilisateurs, /api/events/** goes to service-evenements
# lb:// means "look up the address in Eureka by service name" (no hard-coded IP/port)
spring.cloud.gateway.server.webflux.routes[0].id=service-utilisateurs
spring.cloud.gateway.server.webflux.routes[0].uri=lb://service-utilisateurs
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[1].id=service-evenements
spring.cloud.gateway.server.webflux.routes[1].uri=lb://service-evenements
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/events/**

spring.cloud.gateway.server.webflux.routes[2].id=service-reservation
spring.cloud.gateway.server.webflux.routes[2].uri=lb://service-reservation
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/reservations/**

# Eureka — where to find the registry
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,gateway
